name: Update OpenAPI Specification

# This workflow can be triggered manually
on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-openapi:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Fetch OpenAPI specification
        run: |
          curl -s https://api.vapi.ai/api-json > temp-openapi.json
      
      - name: Verify JSON validity
        run: |
          cat temp-openapi.json | jq . > /dev/null
          if [ $? -ne 0 ]; then
            echo "Error: Invalid JSON received from API endpoint"
            exit 1
          fi
          mv temp-openapi.json ./fern/openapi.json
      
      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet ./fern/openapi.json; then
            echo "No changes detected in OpenAPI specification"
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in OpenAPI specification"
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Create Pull Request
        if: steps.check_changes.outputs.changes_detected == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update OpenAPI specification"
          title: "Update OpenAPI Specification"
          body: |
            This PR updates the OpenAPI specification from the official Vapi API endpoint.
            
            - Auto-generated by the Update OpenAPI Specification workflow
            - Source: https://api.vapi.ai/api-json
            - Generated at: ${{ github.event.repository.updated_at }}
          branch: update-openapi-spec
          base: main
      
      - name: PR Result
        if: steps.check_changes.outputs.changes_detected == 'true'
        run: |
          echo "Pull request created successfully!"
      
      - name: No Changes Result
        if: steps.check_changes.outputs.changes_detected == 'false'
        run: |
          echo "No changes detected in OpenAPI specification. No PR created."
